/*
 * FOUNDATION TOKENS — the bottom of the hierarchy (Foundation → Primitives →
 * Components → Sections). Values are NOT duplicated here: colors/radii live
 * in ONE place (src/index.css :root, the shadcn CSS-variable contract mapped
 * to our brand). This module exposes them as named references so every layer
 * above imports `color.accent`, not the string "var(--accent)" or, worse, a
 * hardcoded hex — that duplication is exactly the bug that slipped into an
 * earlier SidebarNav pass and got caught.
 *
 * Spacing and type ARE real scales (not just CSS var passthroughs) because
 * komanda.html/dashboard.html don't define one centrally — this synthesizes
 * one from the values actually observed across the source pages, so every
 * primitive built on top picks from a shared scale instead of inventing
 * one-off pixel values per component.
 */

/** Color — ONE place, every color, named by role. References to the CSS
 *  custom properties defined in index.css; values live there ONCE, this is
 *  just a typed name for each. (Previously split into `color` (shadcn's
 *  contract slots) and a separate `brand` object (then named by hue: orange/green/warn/plum) —
 *  merged because that split actively hid a bug: shadcn's own `--accent`
 *  slot is its internal hover fill (cream-2, == `muted`), which collided in
 *  name with our real brand orange in the other object. One namespace, no
 *  same-named-different-color trap.) */
export const color = {
  // --- page / surface ---
  // Naming: shadcn-contract slots keep shadcn's names (vendored components
  // read them); our OWN one-offs follow {category}{Role} — textTertiary,
  // surfaceData, surfaceWash, overlay, waveformIdle.
  background: "var(--background)", // cream-2 — the page
  foreground: "var(--foreground)", // cream-12 — ink
  card: "var(--card)", // cream-1 — SOLID panel (glass retired 2026-07-20; shares the panel-warm value with popover deliberately)
  cardForeground: "var(--card-foreground)",
  popover: "var(--popover)", // cream-1 — paper-warm, stays opaque for readability
  popoverForeground: "var(--popover-foreground)",
  textTertiary: "var(--brand-text-tertiary)", // cream-9 — 3rd-level ink (no-data states), one step past mutedForeground. A neutral text tone, not a status color — lives here, not with the semantic roles below.
  surfaceSelected: "var(--brand-surface-selected)", // cream-5 — selected/current neutral fill, one step darker than muted (hover). On a near-white panel selection must go darker, not lighter (white is invisible). SidebarNav active item.

  // --- controls ---
  primary: "var(--primary)", // ink — default filled CTA (dark, not orange)
  primaryForeground: "var(--primary-foreground)",
  secondary: "var(--secondary)", // paper (white) — quiet button, chips
  secondaryForeground: "var(--secondary-foreground)",
  muted: "var(--muted)", // cream-2 — hover fill, tag pills (== shadcn's own --accent slot)
  mutedForeground: "var(--muted-foreground)", // ink-2
  border: "var(--border)", // transparent BY RULE (see DESIGN.md) — do not use for a visible line, use `input`
  input: "var(--input)", // line-2 — the one hairline that's meant to be seen (inputs, dividers)
  ring: "var(--ring)", // == accent — focus ring is brand orange
  destructive: "var(--destructive)", // shadcn's own contract slot — wired to `danger` below (a real red, not accent)

  // --- brand + semantic (komanda's own palette, no shadcn-contract slot) ---
  // Each role is a slice of ONE primitive scale (scales.css, generated by
  // scripts/gen-colors.mjs) by the Radix step grammar — see DESIGN.md →
  // Colors: base = step 9 (the seed, verbatim) / hover = 10 / soft = alpha
  // a3 (composes on any light surface) / softForeground = 11 (guaranteed AA
  // on the tint) / softStrong = 12 (data-grade emphasis). foreground (text
  // on base) is picked by measured WCAG contrast, not assumed white.
  accent: "var(--brand-accent)", // orange-9 #f75506 — THE brand color. One per screen, rare.
  accentForeground: "var(--brand-accent-foreground)",
  accentHover: "var(--brand-accent-hover)", // orange-10
  accentSoft: "var(--brand-accent-soft)", // orange-a3 — translucent tint
  accentSoftForeground: "var(--brand-accent-soft-foreground)", // orange-11
  accentSoftStrong: "var(--brand-accent-soft-strong)", // orange-12 — DATA emphasis on the tint (heatmap fractions); softForeground already passes AA, this is stronger, not a crutch
  accentGradient: "var(--brand-accent-gradient)", // komanda's ONE gradient — .primary.askbtn on the assistant dock

  success: "var(--brand-success)", // jade-9 #1f7a54 — score-band "good" (komanda's own band(): score ≥7)
  successForeground: "var(--brand-success-foreground)",
  successHover: "var(--brand-success-hover)",
  successSoft: "var(--brand-success-soft)",
  successSoftForeground: "var(--brand-success-soft-foreground)",
  successSoftStrong: "var(--brand-success-soft-strong)", // jade-12 — see accentSoftStrong

  warning: "var(--brand-warning)", // ochre-9 #b8862f — score-band "caution" (band(): 5 ≤ score < 7)
  warningForeground: "var(--brand-warning-foreground)",
  warningHover: "var(--brand-warning-hover)",
  warningSoft: "var(--brand-warning-soft)",
  warningSoftForeground: "var(--brand-warning-soft-foreground)",
  warningSoftStrong: "var(--brand-warning-soft-strong)", // ochre-12 — see accentSoftStrong

  // IDENTITY token, not a status. success/warning/danger/accent above say
  // "how good is this?"; roleManager says "WHICH kind is this" — it marks the
  // network-/point-manager role, a category of person, not a judgment. Named
  // by what it marks (not by its plum hue — the hue lives on the `plum`
  // primitive scale). Sibling in spirit to the chart palette (categorical),
  // not to the score bands. Don't reuse it as a generic status; a new
  // role-hue would be roleTrainee/roleSupervisor/… (an identity palette).
  roleManager: "var(--brand-role-manager)", // plum-9 #7a4d7d — the manager-role identity tint (not a score band)
  roleManagerForeground: "var(--brand-role-manager-foreground)",
  roleManagerHover: "var(--brand-role-manager-hover)",
  roleManagerSoft: "var(--brand-role-manager-soft)",
  roleManagerSoftForeground: "var(--brand-role-manager-soft-foreground)",

  danger: "var(--brand-danger)", // brick-9 #b23a2e — real destructive red. NOT accent — neither source page has a red, this is a deliberate addition (see index.css)
  dangerForeground: "var(--brand-danger-foreground)",
  dangerHover: "var(--brand-danger-hover)",
  dangerSoft: "var(--brand-danger-soft)",
  dangerSoftForeground: "var(--brand-danger-soft-foreground)",

  // --- charts ---
  // Categorical data-viz palette — its OWN domain (DESIGN.md → Charts): not
  // scale-derived, not semantic-reuse (the old chart-1/2/5 were literally
  // accent/green/mutedForeground — a meaning collision). Built in OKLCH on
  // one weight band, validated for CVD distinguishability; FIXED order,
  // series 1 always takes chart1. >6 series → facet or "other", never a 7th
  // color. Sequential/heatmap data uses orange scale steps, not these.
  chart1: "var(--chart-1)", // #c66243 clay
  chart2: "var(--chart-2)", // #bea333 gold — <3:1 vs surface: legend/labels required
  chart3: "var(--chart-3)", // #158353 pine
  chart4: "var(--chart-4)", // #2badc1 teal — <3:1 vs surface: legend/labels required
  chart5: "var(--chart-5)", // #5055ab indigo
  chart6: "var(--chart-6)", // #c162a4 magenta
  surfaceData: "var(--brand-surface-data)", // #fbfaf7 — quiet backdrop for data-viz surfaces (dashboard-prototype.html only)
  overlay: "var(--brand-overlay)", // black-a2 — dark low-opacity veil behind a heavily blurred overlay (assistant dock)
  waveformIdle: "var(--brand-waveform-idle)", // #cbb79c — WaveformPlayer's component token: idle bars; playback progress recolors them to accent
  surfaceWash: "var(--brand-surface-wash)", // rgba(0,0,0,.03) — LayeredCard's tinted wrapper (dialog-v2's .rec/.up4-card background); deliberately below black-a1
} as const

type ColorKey = keyof typeof color

/** Keys of `color` that have all 4 role siblings (`XForeground`/`XHover`/
 *  `XSoft`/`XSoftForeground`) — computed at the TYPE level too, not just at
 *  runtime, so `color[`${role}Foreground`]` type-checks under `strict`
 *  without a cast. */
type SemanticRoleKey = {
  [K in ColorKey]: `${K}Foreground` extends ColorKey
    ? `${K}Hover` extends ColorKey
      ? `${K}Soft` extends ColorKey
        ? `${K}SoftForeground` extends ColorKey ? K : never
        : never
      : never
    : never
}[ColorKey]

/** Every "full role" name in `color` — derived from the naming convention
 *  itself (a role is any key with matching `Foreground`/`Hover`/`Soft`/
 *  `SoftForeground` siblings), not a second hand-maintained list. Add a new
 *  role above (all 5 suffixed keys) and it appears here — and in
 *  Foundation/Colors' story, which reads THIS — with zero other edits.
 *  This is the fix for the class of bug `scrim` shipped with (built, wired
 *  into a real component, invisible in Storybook because the demo story
 *  hand-listed variants instead of reading the source object). */
export const semanticRoles = (Object.keys(color) as ColorKey[]).filter((key): key is SemanticRoleKey => {
  if (
    key.endsWith("Foreground") || key.endsWith("Hover") ||
    key.endsWith("Soft") || key.endsWith("SoftForeground")
  ) return false
  return (
    `${key}Foreground` in color && `${key}Hover` in color &&
    `${key}Soft` in color && `${key}SoftForeground` in color
  )
})

/** The `chartN` keys in `color`, in order — same reasoning as
 *  `semanticRoles`: derived from the naming pattern, so a 6th chart color
 *  added to `color` above shows up in Foundation/Colors' Charts story with
 *  no edit there. */
export const chartKeys = (Object.keys(color) as (keyof typeof color)[])
  .filter((key) => /^chart\d+$/.test(key))
  .sort((a, b) => Number(a.slice(5)) - Number(b.slice(5)))

/** Radius scale — named steps over the single --radius token (index.css). */
export const radius = {
  sm: "var(--radius-sm)",
  md: "var(--radius-md)",
  lg: "var(--radius-lg)",
  xl: "var(--radius-xl)",
  "2xl": "var(--radius-2xl)",
  pill: 999,
} as const

/** Spacing scale (px) — synthesized from values actually used across
 *  komanda.html/dashboard.html (6/8/12/16/18/20/24/28...), rounded into a
 *  shared step scale so primitives/components pick from one set. */
export const spacing = {
  none: 0,
  xs: 4,
  sm: 8,
  md: 12,
  base: 16,
  lg: 20,
  xl: 24,
  "2xl": 32,
  "3xl": 40,
  "4xl": 56,
} as const

export type SpacingKey = keyof typeof spacing

/** Type scale (px + line-height) — the three named tokens komanda.html
 *  declares itself (--text-footnote/caption/body) extended upward with the
 *  heading sizes actually found in its markup (18/20/24), plus one larger
 *  step (`display`) for hero-scale contexts not yet exercised by either
 *  source page. */
export const type = {
  footnote: { size: 12, lineHeight: 1.45 }, // var(--text-footnote)
  caption: { size: 14, lineHeight: 1.45 }, // var(--text-caption)
  body: { size: 16, lineHeight: 1.55 }, // var(--text-body)
  subhead: { size: 18, lineHeight: 1.35 },
  title: { size: 20, lineHeight: 1.3 },
  headline: { size: 24, lineHeight: 1.25 },
  display: { size: 32, lineHeight: 1.15 },
} as const

export type TypeKey = keyof typeof type

/** Font family — self-hosted Struve, see brand-overrides.css for @font-face. */
export const font = {
  sans: "var(--font-sans)",
} as const

/** Motion — extracted from komanda.html, where these exact values recur
 *  across independent animations rather than being one-offs. `spring` is
 *  the brand signature (the assistant dock's morph, the modal pop): a
 *  slight overshoot, not a generic ease. Was previously baked inline
 *  wherever needed — the recurring curve is what makes it a token. */
export const motion = {
  /** hover/press feedback (transform, background) */
  fast: "150ms",
  /** small reveals (opacity, chevron rotation) */
  base: "200ms",
  /** panel/dock morphs — pair with `spring` */
  slow: "340ms",
  /** signature overshoot curve — komanda's cubic-bezier(.34,1.3,.5,1) */
  spring: "cubic-bezier(0.34, 1.3, 0.5, 1)",
  /** plain fallback where overshoot would look wrong (color fades) */
  ease: "ease",
} as const

/** Breakpoints (px) — the two real layout switches in the system. NOT a
 *  full responsive scale on purpose: only breakpoints actually exercised
 *  by shipped CSS belong here. CSS files can't import TS — row.css and
 *  SidebarNav.css hard-code these same numbers; if you change one here,
 *  grep the src CSS files for the old value and update in lockstep. */
export const breakpoint = {
  /** TitledRow collapses title-rail to stacked column below this (row.css) */
  rail: 1120,
  /** SidebarNav collapses to mobile below this (SidebarNav.css) */
  sidebar: 760,
} as const
